### ISSUE TITLE
Inquiry: Using `jwtAuthz` in a Route Handler function

### ISSUE THREAD

**Issue by aMahanna** [auth0/express-jwt-authz#48]
Hi! Want to first thank the developers for making `express-jwt-authz` and `express-jwt` 🙌 

### Describe the problem you'd like to have solved

I am trying to use `jwtAuthz` within a Route Handler function, like such:

```javascript
var jwt = require('express-jwt');
var jwtAuthz = require('express-jwt-authz');

var options = {};
app.get('/users',
  jwt({ secret: 'shared_secret' }),
  // jwtAuthz([ 'read:users' ], options),
  function(req, res) {
    jwtAuthz([ 'read:users' ], options) // not sure how to make this work here
  }
);
```

### Additional context

I have the following routes:

```javascript
app.get('/a',
   jwtAuthz(['read:a']),
   ...
);

app.get('/b',
   jwtAuthz(['read:b']),
   ...
);

app.get('/c',
   jwtAuthz(['read:c']),
   ...
);
```

I want to try the following:

```javascript
app.get('/:letter',
   function(req, res) {
     jwtAuthz([ `read:${req.params.letter}` ])
   }
);
```

Hope this makes sense (I am also not sure if this is considered bad practice or not, as I am fairly new to Auth0)

**Comment by adamjmcgrath** [comment]
Hi @aMahanna, thanks for raising this.

Your example is nearly right, you just need to execute the middleware with the request context `jwtAuthz((...])(req, res, next)`.

However, I don't think this is a good idea, mainly from a security point of view. For example if multiple scopes are provided, the user only needs one of the specified scopes to access to route. If I had scope `a` and not `b` - I might be able to trick your route handler into giving me access to `a` by providing both a and b eg. `/a%20b`. I know in your current configuration this wouldn't be possible, but you can imagine some fairly innocent changes to the SDK or your code that might trigger a vulnerability.

It's always better to rely on server configuration rather than user input to configure security features on your server.

There's also usually a performance penalty to initialising a new instance of middleware on every request, since lots of middleware will likely cache work in memory to use across requests.

If you want to shorten your code you could maybe try something like:

```js
for (const route of ['a', 'b', 'c']):
  app.get('/' + route,
   jwtAuthz(['read:' + route]),
   ...
);
```

**Comment by adamjmcgrath** [comment]
(also apologies for the long delay in replying)

**Comment by aMahanna** [comment]
@adamjmcgrath thank you! and no worries on the delay
